package com.aiope2.core.designsystem.theme

import androidx.compose.ui.graphics.Color

// Vivid dark green palette
val PRIMARY = Color(0xFF166C47)
val PRIMARY_DARK = Color(0xFF87D7AA)
val PRIMARY_CONTAINER_DARK = Color(0xFF1B4D35)
val PRIMARY_CONTAINER_LIGHT = Color(0xFFB8F0D2)
val BACKGROUND_DARK = Color(0xFF121213)
val BACKGROUND_LIGHT = Color(0xFFF7F7F7)
val SURFACE_DARK = Color(0xFF121213)
val SURFACE_LIGHT = Color(0xFFF7F7F7)
val SURFACE_VARIANT_DARK = Color(0xFF1C1C1E)
val SURFACE_VARIANT_LIGHT = Color(0xFFE8E8EC)
val ON_SURFACE_DARK = Color(0xFFF9F9F9)
val ON_SURFACE_LIGHT = Color(0xFF202020)
val ON_SURFACE_VARIANT_DARK = Color(0xFFCECECE)
val ON_SURFACE_VARIANT_LIGHT = Color(0xFF646464)
val OUTLINE_VARIANT_DARK = Color(0xFF3C3C3C)
val OUTLINE_VARIANT_LIGHT = Color(0xFFD0D0D0)
val SECONDARY_DARK = Color(0xFFC2C5DD)
val SECONDARY_LIGHT = Color(0xFF595D72)
val SECONDARY_CONTAINER_DARK = Color(0xFF424659)
val SECONDARY_CONTAINER_LIGHT = Color(0xFFDEE1F9)
