#!/usr/bin/env bash
# Regenerate daemon/browser/tranco.txt from the Tranco top-list.
#
# Tranco (https://tranco-list.eu) is a research-grade, manipulation-hardened
# top-sites ranking — the right source for a security allowlist (a naive raw
# popularity list can be gamed by malware/C2 domains).
#
# Usage: scripts/fetch-tranco.sh [N]   (default N=10000)
#
# The list is embedded via go:embed at build time, so this only needs to run
# when refreshing the pinned allowlist (a committed build dependency).
set -euo pipefail

N="${1:-10000}"
OUT="$(dirname "$0")/../browser/tranco.txt"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# Tranco publishes a stable "latest" full-list zip of ranked eTLD+1 domains.
URL="https://tranco-list.eu/top-1m.csv.zip"
echo "Downloading Tranco list..."
curl -fsSL "$URL" -o "$TMP/top-1m.csv.zip"
unzip -p "$TMP/top-1m.csv.zip" > "$TMP/top-1m.csv"

{
  echo "# Tranco top-$N allowlist (eTLD+1, one per line). Generated by fetch-tranco.sh."
  echo "# Source: $URL"
  echo "# Regenerate: scripts/fetch-tranco.sh $N"
  # CSV rows are: rank,domain — take the domain column, top N.
  head -n "$N" "$TMP/top-1m.csv" | cut -d, -f2
} > "$OUT"

echo "Wrote $(wc -l < "$OUT") lines to $OUT"
